name: jay.alcazar
favicon: null
layout_spectrum: 0.8302041608840227
typography_spectrum: 0.82333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#102c3a'
    - '#46a5b7'
    - '#e7438a'
    - '#ffb2a2'
    - '#b8dbe1'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
