name: jay.alcazar
favicon: null
layout_spectrum: 0.8302041608840227
typography_spectrum: 0.82333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e7b81'
    - '#ffffff'
    - '#216b9a'
    - '#8dbe5e'
    - '#61b4e2'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
