name: jay.alcazar
favicon: null
layout_spectrum: 0.8302041608840227
typography_spectrum: 0.82333
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.20108055952005088
  lightness: 0.6609479198232293
  saturation: 0.7034295727498829
  rhythmicContrast: 0.7527843229472637
purpose: []
